name: windig
description: "Your little companion for outdoor activities, providing real-time weather info for your location."
homepage: https://windig.lttl.dev
repository: https://github.com/m5lk3n/windig
publish_to: 'none'

version: 0.0.6+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  adaptive_theme: ^3.7.1+2
  cupertino_icons: ^1.0.8
  flutter_compass: ^0.8.1
  flutter_dotenv: ^6.0.0
  flutter_riverpod: ^3.0.0
  flutter_speed_dial: ^7.0.0
  flutter_secure_storage: ^9.2.4
  geolocator: ^14.0.1
  google_fonts: ^6.3.1
  http: ^1.5.0
  intl: ^0.20.2
  logging: ^1.3.0
  package_info_plus: ^9.0.0
  path_provider: ^2.1.5
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter

  custom_lint: ^0.8.0
  flutter_lints: ^6.0.0
  riverpod_lint: ^3.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - .env
    - assets/icon/icon.png
    - assets/icon/icon-small.png
    - assets/logo/logo.png

flutter_launcher_icons:
  android: true
  adaptive_icon_background: "#00000000"
  adaptive_icon_foreground: "assets/icon/icon.png"
  image_path: "assets/icon/icon.png"
  ios: false
  remove_alpha_ios: false